-- ============================================================
-- MATOSHRI ERP - PHASE 2 DATABASE SCHEMA
-- Run this entire script in Supabase > SQL Editor
-- ============================================================


-- ============================================================
-- TABLE 1: SUBJECTS
-- Stores the catalog of all subjects per branch/year
-- ============================================================
CREATE TABLE IF NOT EXISTS subjects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code     VARCHAR(20) NOT NULL,
    title           VARCHAR(150) NOT NULL,
    branch          VARCHAR(100) NOT NULL,
    year            VARCHAR(20) NOT NULL,
    instructor_name VARCHAR(100),
    instructor_role VARCHAR(50) DEFAULT 'Course Instructor',
    credits         INT DEFAULT 4,
    type            VARCHAR(30) DEFAULT 'Theory' -- Theory or Lab
);

-- Disable RLS for easy access
ALTER TABLE subjects DISABLE ROW LEVEL SECURITY;

-- Insert Subjects for "Artificial Intelligence and Data Science" (example branch)
INSERT INTO subjects (course_code, title, branch, year, instructor_name, instructor_role, credits, type) VALUES
('107008', 'Engineering Mathematics - III', 'Artificial Intelligence and Data Science', '3rd Year', 'Dr. Savita Badve', 'Course Instructor', 4, 'Theory'),
('CSL601', 'Machine Learning', 'Artificial Intelligence and Data Science', '3rd Year', 'Prof. Kiran Shivade', 'Course Instructor', 4, 'Theory'),
('CSL602', 'Data Warehousing & Mining', 'Artificial Intelligence and Data Science', '3rd Year', 'Prof. Snehal Patil', 'Course Instructor', 3, 'Theory'),
('CSL603', 'Natural Language Processing', 'Artificial Intelligence and Data Science', '3rd Year', 'Dr. Amol Dhumale', 'Course Instructor', 3, 'Theory'),
('CSL604', 'Computer Vision', 'Artificial Intelligence and Data Science', '3rd Year', 'Prof. Mayuri Lokhande', 'Course Instructor', 3, 'Theory'),
('CSP601', 'Machine Learning Lab', 'Artificial Intelligence and Data Science', '3rd Year', 'Prof. Kiran Shivade', 'Lab Instructor', 2, 'Lab'),
-- Add a few for Computer Engineering for variety
('107008', 'Engineering Mathematics - III', 'Computer Engineering', '3rd Year', 'Dr. Savita Badve', 'Course Instructor', 4, 'Theory'),
('CEC601', 'Computer Networks', 'Computer Engineering', '3rd Year', 'Prof. Rahul Desai', 'Course Instructor', 4, 'Theory'),
('CEC602', 'Database Management Systems', 'Computer Engineering', '3rd Year', 'Prof. Priya Sharma', 'Course Instructor', 3, 'Theory'),
('CEC603', 'Software Engineering', 'Computer Engineering', '3rd Year', 'Prof. Vikram Joshi', 'Course Instructor', 3, 'Theory'),
('CEC604', 'Operating Systems', 'Computer Engineering', '3rd Year', 'Dr. Neha Kulkarni', 'Course Instructor', 3, 'Theory'),
('CEP601', 'Networking Lab', 'Computer Engineering', '3rd Year', 'Prof. Rahul Desai', 'Lab Instructor', 2, 'Lab');


-- ============================================================
-- TABLE 2: ATTENDANCE_RECORDS
-- Tracks each lecture's presence/absence per student per subject
-- ============================================================
CREATE TABLE IF NOT EXISTS attendance_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_prn     VARCHAR(20) NOT NULL, -- Matches students.prn_number
    subject_id      BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
    date            DATE NOT NULL,
    status          VARCHAR(10) NOT NULL CHECK (status IN ('Present', 'Absent', 'Late'))
);

ALTER TABLE attendance_records DISABLE ROW LEVEL SECURITY;

-- Insert sample attendance for student PRN '25EN02U009F' (Rushal Bangar)
-- (Run after inserting subjects so IDs exist)
-- Using the first 6 Subject IDs (IDs 1-6 from the insert above)
INSERT INTO attendance_records (student_prn, subject_id, date, status) VALUES
-- Eng. Math III (subject_id = 1)
('25EN02U009F', 1, '2026-01-06', 'Present'), ('25EN02U009F', 1, '2026-01-08', 'Present'),
('25EN02U009F', 1, '2026-01-10', 'Absent'),  ('25EN02U009F', 1, '2026-01-13', 'Present'),
('25EN02U009F', 1, '2026-01-15', 'Present'), ('25EN02U009F', 1, '2026-01-17', 'Present'),
('25EN02U009F', 1, '2026-01-20', 'Present'), ('25EN02U009F', 1, '2026-01-22', 'Absent'),
('25EN02U009F', 1, '2026-01-24', 'Present'), ('25EN02U009F', 1, '2026-01-27', 'Present'),
-- Machine Learning (subject_id = 2)
('25EN02U009F', 2, '2026-01-07', 'Present'), ('25EN02U009F', 2, '2026-01-09', 'Present'),
('25EN02U009F', 2, '2026-01-11', 'Present'), ('25EN02U009F', 2, '2026-01-14', 'Late'),
('25EN02U009F', 2, '2026-01-16', 'Present'), ('25EN02U009F', 2, '2026-01-18', 'Present'),
('25EN02U009F', 2, '2026-01-21', 'Present'), ('25EN02U009F', 2, '2026-01-23', 'Present'),
('25EN02U009F', 2, '2026-01-25', 'Present'), ('25EN02U009F', 2, '2026-01-28', 'Absent'),
-- Data Warehousing (subject_id = 3)
('25EN02U009F', 3, '2026-01-06', 'Present'), ('25EN02U009F', 3, '2026-01-08', 'Absent'),
('25EN02U009F', 3, '2026-01-10', 'Absent'),  ('25EN02U009F', 3, '2026-01-13', 'Present'),
('25EN02U009F', 3, '2026-01-15', 'Present'), ('25EN02U009F', 3, '2026-01-17', 'Absent'),
('25EN02U009F', 3, '2026-01-20', 'Present'), ('25EN02U009F', 3, '2026-01-22', 'Present'),
-- NLP (subject_id = 4)
('25EN02U009F', 4, '2026-01-07', 'Present'), ('25EN02U009F', 4, '2026-01-09', 'Present'),
('25EN02U009F', 4, '2026-01-11', 'Present'), ('25EN02U009F', 4, '2026-01-14', 'Present'),
('25EN02U009F', 4, '2026-01-16', 'Present'), ('25EN02U009F', 4, '2026-01-18', 'Present'),
-- Computer Vision (subject_id = 5)
('25EN02U009F', 5, '2026-01-06', 'Present'), ('25EN02U009F', 5, '2026-01-08', 'Present'),
('25EN02U009F', 5, '2026-01-10', 'Present'), ('25EN02U009F', 5, '2026-01-13', 'Absent'),
('25EN02U009F', 5, '2026-01-15', 'Present'), ('25EN02U009F', 5, '2026-01-17', 'Present'),
('25EN02U009F', 5, '2026-01-20', 'Present'), ('25EN02U009F', 5, '2026-01-22', 'Present'),
-- ML Lab (subject_id = 6)
('25EN02U009F', 6, '2026-01-09', 'Present'), ('25EN02U009F', 6, '2026-01-16', 'Present'),
('25EN02U009F', 6, '2026-01-23', 'Absent'),  ('25EN02U009F', 6, '2026-01-30', 'Present');


-- ============================================================
-- TABLE 3: FEE_TRANSACTIONS
-- Tracks fee invoices and payments per student
-- ============================================================
CREATE TABLE IF NOT EXISTS fee_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_prn         VARCHAR(20) NOT NULL,
    description         VARCHAR(200) NOT NULL,
    amount              DECIMAL(10, 2) NOT NULL,
    transaction_type    VARCHAR(10) NOT NULL CHECK (transaction_type IN ('Invoice', 'Payment')),
    date                DATE NOT NULL,
    semester            VARCHAR(20),
    status              VARCHAR(10) DEFAULT 'Pending' CHECK (status IN ('Paid', 'Pending'))
);

ALTER TABLE fee_transactions DISABLE ROW LEVEL SECURITY;

-- Insert fee data for student Rushal Bangar
INSERT INTO fee_transactions (student_prn, description, amount, transaction_type, date, semester, status) VALUES
-- Invoices (what they owe)
('25EN02U009F', 'Tuition Fees - Sem V', 42000.00, 'Invoice', '2026-01-01', 'Semester 5', 'Pending'),
('25EN02U009F', 'Exam Fees - End Sem', 2500.00, 'Invoice', '2026-01-05', 'Semester 5', 'Paid'),
('25EN02U009F', 'Library & Lab Charges', 5000.00, 'Invoice', '2026-01-05', 'Semester 5', 'Paid'),
('25EN02U009F', 'Bus Pass (Annual)', 15000.00, 'Invoice', '2025-07-01', 'Annual', 'Paid'),
-- Payments (what they have paid)
('25EN02U009F', 'Online Payment - Exam Fee', 2500.00, 'Payment', '2026-01-10', 'Semester 5', 'Paid'),
('25EN02U009F', 'Online Payment - Lab Charges', 5000.00, 'Payment', '2026-01-11', 'Semester 5', 'Paid'),
('25EN02U009F', 'DD Payment - Bus Pass', 15000.00, 'Payment', '2025-07-15', 'Annual', 'Paid');


-- ============================================================
-- TABLE 4: EXAM_RESULTS
-- Stores a student's marks per subject per semester
-- ============================================================
CREATE TABLE IF NOT EXISTS exam_results (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_prn     VARCHAR(20) NOT NULL,
    subject_id      BIGINT REFERENCES subjects(id) ON DELETE CASCADE,
    semester        VARCHAR(20),
    marks_obtained  DECIMAL(5,2) NOT NULL,
    max_marks       DECIMAL(5,2) NOT NULL DEFAULT 100,
    grade           VARCHAR(5),
    grade_points    DECIMAL(3,1)
);

ALTER TABLE exam_results DISABLE ROW LEVEL SECURITY;

-- Insert Exam Results for Rushal Bangar (Semester 4 - Previous Sem)
INSERT INTO exam_results (student_prn, subject_id, semester, marks_obtained, max_marks, grade, grade_points) VALUES
('25EN02U009F', 1, 'Semester 4', 78.00, 100, 'B+', 7.0),
('25EN02U009F', 2, 'Semester 4', 85.00, 100, 'A',  8.0),
('25EN02U009F', 3, 'Semester 4', 72.00, 100, 'B',  6.0),
('25EN02U009F', 4, 'Semester 4', 90.00, 100, 'O',  10.0),
('25EN02U009F', 5, 'Semester 4', 88.00, 100, 'A+', 9.0),
('25EN02U009F', 6, 'Semester 4', 92.00, 100, 'O',  10.0);

-- ============================================================
-- DONE! Your database is now ready for all 4 ERP modules.
-- ============================================================
